export default {
  SAVE: "BOOKS_SAVE",
  SEARCH_AUTHORS: "BOOKS_SEARCH_AUTHORS",
  SEARCH_PUBLISHER: "BOOKS_SEARCH_PUBLISHER",
  SEARCH_CLASSES: "BOOKS_SEARCH_CLASSES",
  GET_SEQUENCE: "BOOKS_GET_SEQUENCE",
  CHECK_SEQUENCE: "BOOKS_CHECK_SEQUENCE",
  SEARCH: "BOOKS_SEARCH",
  LOOKUP: "BOOKS_LOOCKUP",
  DELETE: "BOOKS_DELETE",
  IMPORT: "BOOKS_IMPORT",
  DOWNLOAD_CSV_EXAMPLE: "BOOKS_DOWNLOAD_CSV_EXAMPLE",
};
